[config]
default_to_workspace = false

[tasks.wasm32-target]
install_script = '''
    if [ "$(rustup target list | grep wasm32-unknown-unknown | grep installed)" = "" ];
    then
        rustup target add wasm32-unknown-unknown;
    fi
'''

[tasks.client-build]
dependencies = [ "wasm32-target" ]
script = [
    "vertigo build --dest-dir=build --public-path=/build"
]

[tasks.app-serve]
    command = "cargo"
    args = [ "run", "--bin", "server" ]
[tasks.app-serve.env]
    "RUST_LOG" = "info"
    "HTTP_HOST" = "0.0.0.0"
    "HTTP_PORT" = "4000"

[tasks.app-start]
dependencies = [
    "client-build",
]
run_task = "app-serve"


[tasks.clippy]
    command = "cargo"
    args = [ "clippy"]

[tasks.app-my-start]
dependencies = ["clippy"]
run_task = "app-start"
[tasks.app-my-start.env]
"GIT_REPO" = "../notatki_dane"


[tasks.app-my-start-watch]
command = "cargo"
args = [ "watch", "--watch", "./panel", "--delay", "0.5", "-x", "make app-my-start" ]




[tasks.clippy-wasm32]
dependencies = [ "wasm32-target" ]
command = "cargo"
args = [
    "clippy", "--all-features", "--target", "wasm32-unknown-unknown",
    "-p", "panel/common", "-p", "panel/client", "-p", "panel/server"
]
