
POST http://0.0.0.0:4000/save_content
Content-Type: application/json

{
    "path": ["_testowy","1"],
    "prev_hash": "6c58864a2fd40dca73e3b9c49586ae7b2186e38f",
    "new_content": "Jakaś kolejna nowa dsadasdasdasdas"
}


###



POST http://0.0.0.0:4000/create_file
Content-Type: application/json

{
    "path": ["spiski", "nazisci argentyna"],
    "new_path": ["Nowa szwabia"],
    "new_content": "a"
}


###

POST http://0.0.0.0:4000/rename_item
Content-Type: application/json

{
    "path": ["_testowy"],
    "prev_name": "aaaa",
    "prev_hash": "7284ab4d2836271d66b988ae7d037bd6ef0d5d15",
    "new_name": "aaaa=111"
}

###

POST http://0.0.0.0:4000/delete_item
Content-Type: application/json

{
    "path": ["_testowy", "3=111"],
    "hash": "52cee5da94451abd3fc17a2c831918861ac85fd7"
}

###

POST http://0.0.0.0:4000/create_dir
Content-Type: application/json

{
    "path": ["_testowy"],
    "dir": "pusty_katalog"
}

###
GET http://0.0.0.0:3000/
###

POST http://0.0.0.0:3000/

###

POST http://0.0.0.0:3000/users

{
    "username": "Ambrozy"
}

####

GET http://0.0.0.0:3000/root

####

POST http://0.0.0.0:3000/users
Content-Type: application/json

{
    "username": "Ambrozy"
}

