[package]
name = "server"
version = "0.1.0"
authors = ["Grzegorz Szeliga <grzegorz.szeliga@twoupdigital.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.125", features = ["derive", "rc"] }
serde_json = "1.0.64"
log = "0.4.14"
envy = "0.4.2"
pretty_env_logger = "0.4"
futures = "0.3.14"
git2 = "0.13.18"

tokio = { version = "1.5.0", features = ["full"] }
warp = "0.3.1"

common={path="../common"}

