[package]
name = "server"
version = "0.1.0"
authors = ["Grzegorz Szeliga <grzegorz.szeliga@twoupdigital.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.130", features = ["derive", "rc"] }
serde_json = "1.0.72"
log = "0.4.14"
envy = "0.4.2"
pretty_env_logger = "0.4"
futures = "0.3.18"
git2 = "0.13.25"

tokio = { version = "1.14.0", features = ["full"] }
axum = "0.4"
tower-http = { version = "0.1.2", features = ["fs", "trace"] }

common={path="../common"}

